spring:
  application:
    name: turbine
server:
  port: 18005
eureka:
  client:
    service-url:
      defaultZone: http://localhost:18001/eureka
turbine:
  app-config: eureka-consumer
  cluster-name-expression: new String("default")
  combine-host-port: true