spring:
  application:
    name: api-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:18000/eureka
server:
  port: 18007
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always