server:
  port: 18010
spring:
  application:
    name: admin-server
eureka:
  client:
    service-url:
      defaultZone: http://172.17.0.4:18000/eureka,http://172.17.0.30:18000/eureka,http://172.17.0.103:18000/eureka