spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/summerandwinter/config-repo
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 172.17.0.12
    username: admin
    password: admin
    port: 5672
server:
  port: 18006
eureka:
  client:
    service-url:
      defaultZone: http://localhost:18000/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always