spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/summerandwinter/config-repo
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 172.17.0.12
server:
  port: 18006
eureka:
  client:
    service-url:
      defaultZone: http://172.17.0.4:18000/eureka,http://172.17.0.30:18000/eureka,http://172.17.0.103:18000/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always