server:
  port: 18000
spring:
  application:
    name: eureka-server
eureka:
  instance:
    #hostname: node01
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.17.0.4:18000/eureka,http://172.17.0.30:18000/eureka