server:
  port: 18003
spring:
  application:
    name: eureka-consumer
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:19411/
  rabbitmq:
    host: 172.17.0.12
    username: admin
    password: admin
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:18000/eureka
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always